plugins {
    id 'fabric-loom' version "${loom_version}"
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
    maven { url = "https://maven.terraformersmc.com/" }
    maven { url = "https://maven.nucleoid.xyz" }
    maven {url = "https://api.modrinth.com/maven"}
    maven { url ="https://maven.ladysnake.org/releases" }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    // Trinkets (opcional en runtime; el mod funciona sin él)
    modCompileOnly "maven.modrinth:trinkets-polymer:3.11.0-beta.1+polymerport.4"
    modCompileOnly ('eu.pb4:sgui:1.12.0+1.21.11')
    modCompileOnly ('eu.pb4:player-data-api:0.9.1+1.21.11')
    modCompileOnly("org.ladysnake.cardinal-components-api:cardinal-components-base:7.3.0")
    modCompileOnly("org.ladysnake.cardinal-components-api:cardinal-components-entity:7.3.0")

    // Se añadirá cuando metamos el primer mixin (p.ej. el spawn de meteoros en el mundo):
    // annotationProcessor("io.github.llamalad7:mixinextras-fabric:0.4.1")
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
    withSourcesJar()
}
