org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties — 1.21.11 (https://fabricmc.net/develop)
minecraft_version=1.21.11
loader_version=0.18.2
loom_version=1.15.+

# Fabric API
fabric_version=0.140.2+1.21.11

# Mod Properties
mod_version=1.0.0+1.21.11
maven_group=net.meteor
archives_base_name=fallingmeteors
